In [13]:
%run model.ipynb

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27481 entries, 0 to 27480
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   textID         27481 non-null  object
 1   text           27480 non-null  object
 2   selected_text  27480 non-null  object
 3   sentiment      27481 non-null  object
dtypes: object(4)
memory usage: 858.9+ KB
         textID text selected_text sentiment
314  fdb77c3752  NaN           NaN   neutral
<class 'pandas.core.frame.DataFrame'>
Int64Index: 27480 entries, 0 to 27480
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   textID         27480 non-null  object
 1   text           27480 non-null  object
 2   selected_text  27480 non-null  object
 3   sentiment      27480 non-null  object
dtypes: object(4)
memory usage: 1.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3534 entries, 0 to 3533
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   textID     3534 non-null   object
 1   text       3534 non-null   object
 2   sentiment  3534 non-null   object
dtypes: object(3)
memory usage: 83.0+ KB
542
76
{'neutral': 839, 'positive': 715, 'negative': 602}
Sons of ****,
0.6546512676611831
1.000000    11851
0.000000     2247
0.500000     1122
0.333333      934
0.250000      743
            ...
0.684211        1
0.521739        1
0.192308        1
0.764706        1
0.107143        1
Name: score, Length: 207, dtype: int64

In [14]:
tweet_tst['text']

0       last session of the day  http://twitpic.com/67ezh
1        shanghai is also really exciting (precisely -...
2       recession hit veronique branquinho, she has to...
3                                             happy bday!
4                  http://twitpic.com/4w75p - i like it!!
                              ...
3529    its at 3 am, im very tired but i can`t sleep  ...
3530    all alone in this old house again.  thanks for...
3531     i know what you mean. my little dog is sinkin...
3532    _sutra what is your next youtube video gonna b...
3533     http://twitpic.com/4woj2 - omgssh  ang cute n...
Name: text, Length: 3534, dtype: object

In [15]:
tweet_tst

          textID                                               text sentiment
0     f87dea47db  last session of the day  http://twitpic.com/67ezh   neutral
1     96d74cb729   shanghai is also really exciting (precisely -...  positive
2     eee518ae67  recession hit veronique branquinho, she has to...  negative
3     01082688c6                                        happy bday!  positive
4     33987a8ee5             http://twitpic.com/4w75p - i like it!!  positive
...          ...                                                ...       ...
3529  e5f0e6ef4b  its at 3 am, im very tired but i can`t sleep  ...  negative
3530  416863ce47  all alone in this old house again.  thanks for...  positive
3531  6332da480c   i know what you mean. my little dog is sinkin...  negative
3532  df1baec676  _sutra what is your next youtube video gonna b...  positive
3533  469e15c5a8   http://twitpic.com/4woj2 - omgssh  ang cute n...  positive

[3534 rows x 3 columns]

In [16]:
tweet_tst.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3534 entries, 0 to 3533
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   textID     3534 non-null   object
 1   text       3534 non-null   object
 2   sentiment  3534 non-null   object
dtypes: object(3)
memory usage: 83.0+ KB

In [37]:
tweet_tst['predicted_text']=''
for i,rows in tweet_tst.iterrows():
    
    tol=0.001
    selected_text=choose_selected_text(rows,tol)
    #print(selected_text)
    tweet_tst.loc[tweet_tst['textID'] == rows['textID'], ['predicted_text']] = selected_text

In [38]:
tweet_tst

,textID,text,sentiment,predicted_text
0,f87dea47db,last session of the day http://twitpic.com/67ezh,neutral,last session of the day http://twitpic.com/67ezh
1,96d74cb729,shanghai is also really exciting (precisely -...,positive,good
2,eee518ae67,"recession hit veronique branquinho, she has to...",negative,shame!
3,01082688c6,happy bday!,positive,happy
4,33987a8ee5,http://twitpic.com/4w75p - i like it!!,positive,http://twitpic.com/4w75p - i like it!!
...,...,...,...,...
3529,e5f0e6ef4b,"its at 3 am, im very tired but i can`t sleep ...",negative,tired
3530,416863ce47,all alone in this old house again. thanks for...,positive,thanks
3531,6332da480c,i know what you mean. my little dog is sinkin...,negative,i know what you mean. my little dog is sinkin...
3532,df1baec676,_sutra what is your next youtube video gonna b...,positive,love
3533,469e15c5a8,http://twitpic.com/4woj2 - omgssh ang cute n...,positive,cute

In [39]:
final_sub=pd.DataFrame()
final_sub['textID']=tweet_tst['textID']

In [40]:
final_sub['selected_text']=tweet_tst['predicted_text']
final_sub

          textID                                      selected_text
0     f87dea47db  last session of the day  http://twitpic.com/67ezh
1     96d74cb729                                               good
2     eee518ae67                                             shame!
3     01082688c6                                              happy
4     33987a8ee5             http://twitpic.com/4w75p - i like it!!
...          ...                                                ...
3529  e5f0e6ef4b                                              tired
3530  416863ce47                                             thanks
3531  6332da480c   i know what you mean. my little dog is sinkin...
3532  df1baec676                                               love
3533  469e15c5a8                                               cute

[3534 rows x 2 columns]

In [44]:
final_sub.to_csv('sub.csv')